server: 
  port: 8081
spring: 
  datasource: 
    url: jdbc:postgresql://localhost:5432/myretail
  data:
    mongodb:
      host: localhost
      port: 27017
      database: myRetailProduct
      repositories.enabled: true